services:
  remote-sensing:
    build: .
    command: sleep infinity
    volumes:
      - ./:/src
      - /media/data/active/Remotesensing/Patches:/data
    deploy: 
       resources: 
         reservations: 
           devices: 
             - driver: nvidia 
               count: 2 
               capabilities: [gpu]
